### ISSUE TITLE
Regex Error at generating output files step

### ISSUE THREAD

**Issue by hyobyun** [jsdoc3/jsdoc#1071]
I'm getting this error on both 0.12.7 and 4.0. with jsdoc version 3.3.3
The parsing completes with no problems, but on the last step I get this error, but I'm having trouble narrowing down the cause. Any help would be greatly appreciated. 

    DEBUG: Finished parsing source files.
    DEBUG: Indexing doclets...
    DEBUG: Adding inherited symbols, mixins, and interface implementations...
    DEBUG: Adding borrowed doclets...
    DEBUG: Post-processing complete.
    Generating output files...undefined:19
                paramRegExp = new RegExp('^(?:' + parentParam.name + '(?:\\[\\])*)\\.(.+)$');
                              ^

    SyntaxError: Invalid regular expression: /^(?:func(parentKey,(?:\[\])*)\.(.+)$/: Unterminated group
        at new RegExp (native)
        at eval (eval at <anonymous> (D:\THEPATH\node_modules\underscore\underscore.js:1329:20), <anonymous>:19:27)
        at Array.forEach (native)
        at eval (eval at <anonymous> (D:\THEPATH\node_modules\underscore\underscore.js:1329:20), <anonymous>:11:12)
        at template (D:\THEPATH\node_modules\underscore\underscore.js:1336:21)
        at exports.Template.partial (D:\THEPATH\node_modules\jsdoc\lib\jsdoc\template.js:60:29)
        at eval (eval at <anonymous> (D:\THEPATH\node_modules\underscore\underscore.js:1329:20), <anonymous>:56:14)
        at template (D:\THEPATH\node_modules\underscore\underscore.js:1336:21)
        at exports.Template.partial (D:\THEPATH\node_modules\jsdoc\lib\jsdoc\template.js:60:29)
        at eval (eval at <anonymous> (D:\THEPATH\node_modules\underscore\underscore.js:1329:20), <anonymous>:204:14)

**Comment by hyobyun** [comment]
Figured it out:
The following line was responsible: 

     @param func(parentKey, parentObj, key, value) {function} visitor function that takes parentKey,     parentObj, key, and value

**Comment by hegemonic** [comment]
That's a severely malformed `@param` tag, so you shouldn't expect it to generate reasonable output. But I agree that JSDoc shouldn't crash in this case.
