### ISSUE TITLE
JSXAttribute can have null value

### ISSUE THREAD

**Issue by MitMaro** [jsdoc3/jsdoc#1085]
## Problem Description

When parsing JSX that uses the shorthand boolean property JSDoc3 will crash. This is because, in that case, the JSXAttribute will have a value of null.

## Exception that occurs

    TypeError: Cannot set property 'parent' of null
        at cb (node_modules/jsdoc/lib/jsdoc/src/walker.js:558:21)
        at Object.walkers.(anonymous function) [as JSXAttribute] (node_modules/jsdoc/lib/jsdoc/src/walker.js:278:5)
        at cb (node_modules/jsdoc/lib/jsdoc/src/walker.js:570:33)
        at Object.walkers.(anonymous function) [as JSXOpeningElement] (node_modules/jsdoc/lib/jsdoc/src/walker.js:321:9)
        at cb (node_modules/jsdoc/lib/jsdoc/src/walker.js:570:33)
        at Object.walkers.(anonymous function) [as JSXElement] (node_modules/jsdoc/lib/jsdoc/src/walker.js:286:5)
        at cb (node_modules/jsdoc/lib/jsdoc/src/walker.js:570:33)
        at Object.walkers.(anonymous function) [as ExpressionStatement] (node_modules/jsdoc/lib/jsdoc/src/walker.js:212:5)
        at cb (node_modules/jsdoc/lib/jsdoc/src/walker.js:570:33)
        at Object.walkers.(anonymous function) (node_modules/jsdoc/lib/jsdoc/src/walker.js:95:9)
        at cb (node_modules/jsdoc/lib/jsdoc/src/walker.js:570:33)
        at Walker._recurse (node_modules/jsdoc/lib/jsdoc/src/walker.js:577:5)
        at Walker.recurse (node_modules/jsdoc/lib/jsdoc/src/walker.js:587:22)
        at Parser._walkAst (node_modules/jsdoc/lib/jsdoc/src/parser.js:268:18)
        at Parser._parseSourceCode (node_modules/jsdoc/lib/jsdoc/src/parser.js:259:18)
        at Parser.parse (node_modules/jsdoc/lib/jsdoc/src/parser.js:180:18)

## Minimal Test Case

Create a file, test.jsx, containing the line:

    <div myBool />

Run with the command:

    jsdoc ./test.jsx

## AST snippet

    JSXIdentifier { type: 'JSXIdentifier',
      name: 'div',
      range: [ 1, 4 ],
      loc: { start: { line: 1, column: 1 }, end: { line: 1, column: 4 } } }
    JSXAttribute { type: 'JSXAttribute',
      name:
      { type: 'JSXIdentifier',
        name: 'myBool',
        range: [ 5, 11 ],
        loc: { start: [Object], end: [Object] } },
      value: null,
        range: [ 5, 11 ],
        loc: { start: { line: 1, column: 5 }, end: { line: 1, column: 11 } } }
    JSXIdentifier { type: 'JSXIdentifier',
      name: 'myBool',
      range: [ 5, 11 ],
      loc: { start: { line: 1, column: 5 }, end: { line: 1, column: 11 } } }

## Notes

From looking into the Esprima-FB fork, which Espree based it's JSX implementation on, this is by design. Source: https://github.com/facebook/esprima/blob/fb-harmony/esprima.js#L2334

In JSDoc3 the parser tries to parse the value on [line 278 in walker.js](https://github.com/jsdoc3/jsdoc/blob/65ede6e4fbf8ae8756e434ed937dc4fc94bd76fb/lib/jsdoc/src/walker.js#L278) passing a null node.

**Comment by hegemonic** [comment]
Fixed on master. Thanks for the heads up!
