### ISSUE TITLE
JSDoc breaks on ExperimentalRestProperty

### ISSUE THREAD

**Issue by yaycmyk** [jsdoc3/jsdoc#1091]
Code with the shape of:

```js
return {
    ...accumulator,
    route: (ptr = ptr[segment]),
};
```

Emits this error stack:

```shell
/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:560
        currentScope = getCurrentScope(cbState.scopes);
                                              ^

TypeError: Cannot read property 'scopes' of undefined
    at cb (/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:560:47)
    at Object.walkers.(anonymous function) (/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:167:5)
    at cb (/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:570:33)
    at Object.walkers.(anonymous function) (/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:389:9)
    at cb (/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:570:33)
    at Object.walkers.(anonymous function) [as ReturnStatement] (/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:412:9)
    at cb (/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:570:33)
    at Object.walkers.(anonymous function) (/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:95:9)
    at cb (/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:570:33)
    at Object.walkers.(anonymous function) [as IfStatement] (/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:247:5)
    at cb (/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:570:33)
    at Object.walkers.(anonymous function) (/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:95:9)
    at cb (/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:570:33)
    at Object.walkers.(anonymous function) (/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:78:5)
    at cb (/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:570:33)
    at Object.walkers.(anonymous function) (/Users/esj/code/appkit/node_modules/jsdoc/lib/jsdoc/src/walker.js:108:13)
```

If I comment out the rest expression, JSDoc doesn't break. (This is on the dev version)

**Comment by hegemonic** [comment]
Thanks for the report and the fix! I committed a better fix, which calls the node's callback with the appropriate arguments.

**Comment by yaycmyk** [comment]
@hegemonic right on, thanks :)
