### ISSUE TITLE
@callback causing a regular expression unterminated group error

### ISSUE THREAD

**Issue by white-donkey** [jsdoc3/jsdoc#1095]
I need some help with a problem that I am having.  I am not sure if I am doing something wrong or if I have stumbled into a bug in JsDoc.  I am using version 3.3.3 of JsDoc and I have it installed globally running from the command line using the default template.

I have a class called Cii_Flow which is in the namespace cii_flow that contains multiple callback functions.  JsDoc (v3.3.3) is happy with all of them except for one and to me that one appears to follow the same pattern as all of the rest so I can't, for the life of me, figure out what I may be doing wrong.

JsDoc is happy with this...
```
/** 
 * A user supplied callback routine to be called when an element is 
 * created.  The callback is registered by the user with a call to 
 * [registerOnCreate()]{@link cii_flow.Cii_Flow#registerOnCreate}. The callback 
 * routine must handle any of the registered element types that were registered 
 * with [registerOnCreate()]{@link cii_flow.Cii_Flow#registerOnCreate}.  The 
 * callback routine will not be called for any element types that were not 
 * registered. 
 * @callback cii_flow.Cii_Flow.create_cb
 * @param {object} item - The element that is being created.  This can be 
 *  	  one of the following types. {@link cii_flow_block.Block}, {@link
 *  	  cii_flow_connector.Connector} or {@link cii_flow_endpoint.Endpoint}.
 * @return Nothing
 */
```
But it complains about the following...
```
/** 
 * A user supplied callback routine to be called when a user stops dragging an 
 * element.  The callback is registered by the user with a call to 
 * [registerOnDragStop()]{@link cii_flow.Cii_Flow#registerOnDragStop}. The 
 * callback routine must handle any of the registered element types that were 
 * registered with [registerOnDragStop()]{@link 
 * cii_flow.Cii_Flow#registerOnDragStop}. The callback routine will not be 
 * called for any element types that were not registered. 
 * @callback cii_flow.Cii_Flow.drag_stop_cb 
 * @param {object} item - The element that was being dragged.  At this time only
 *  	  {@link cii_flow_block.Block} is supported.
 * @param (number} x - The x position where the drag stopped. 
 * @param (number} y - The y position where the drag stopped.
 * @return Nothing
 */
```
If I delete the @callback line for drag_stop_cb then JsDoc is happy again.

The error that I am getting from JsDoc is the following...
```
undefined:19
            paramRegExp = new RegExp('^(?:' + parentParam.name + '(?:\\[\\])*)
                          ^
SyntaxError: Invalid regular expression: /^(?:(number}(?:\[\])*)\.(.+)$/: Unterminated group
    at new RegExp (native)
    at eval (eval at <anonymous> (C:\Users\kbianculli\AppData\Roaming\npm\node_modules\jsdoc\node_modules\underscore\underscore.js:1329:20), <anonymous>:19:27)
    at Array.forEach (native)
    at eval (eval at <anonymous> (C:\Users\kbianculli\AppData\Roaming\npm\node_modules\jsdoc\node_modules\underscore\underscore.js:1329:20), <anonymous>:11:12)
    at template (C:\Users\kbianculli\AppData\Roaming\npm\node_modules\jsdoc\node_modules\underscore\underscore.js:1336:21)
    at exports.Template.partial (C:\Users\kbianculli\AppData\Roaming\npm\node_modules\jsdoc\lib\jsdoc\template.js:60:29)
    at eval (eval at <anonymous> (C:\Users\kbianculli\AppData\Roaming\npm\node_modules\jsdoc\node_modules\underscore\underscore.js:1329:20), <anonymous>:56:14)
    at template (C:\Users\kbianculli\AppData\Roaming\npm\node_modules\jsdoc\node_modules\underscore\underscore.js:1336:21)
    at exports.Template.partial (C:\Users\kbianculli\AppData\Roaming\npm\node_modules\jsdoc\lib\jsdoc\template.js:60:29)
    at eval (eval at <anonymous> (C:\Users\kbianculli\AppData\Roaming\npm\node_modules\jsdoc\node_modules\underscore\underscore.js:1329:20), <anonymous>:219:14)
```

Thanks in advance.

**Comment by white-donkey** [comment]
I figured out my own problem.  It was being caused by the @param (number}.  Notice the parentheses instead of a bracket before number.  Once I fixed this and changed them to {number} it worked.  Deleting the @callback line made it work because without the @callback drag_stop_cb became a variable and as such the @param attributes were ignored.
