### ISSUE TITLE
Exception when using E4X attribute selector

### ISSUE THREAD

**Issue by CardContact** [jsdoc3/jsdoc#1101]
The following piece of code in a Smart Card Shell script using an E4X attribute selector

	for each (var job in lst.job) {
		sellst.push(job.@id + ": " + job.@description);
	}

leads to

org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalArgumentException: No enum constant org.jsdoc.AstBuilder.NodeTypes.XmlMemberGet
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_rhino_jsdoc_src_astbuilder_js_105._c_anonymous_2(Unknown Source)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_rhino_jsdoc_src_astbuilder_js_105.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_lib_jsdoc_src_parser_js_102._c_anonymous_17(Unknown Source)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_lib_jsdoc_src_parser_js_102.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_lib_jsdoc_src_parser_js_102._c_anonymous_10(Unknown Source)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_lib_jsdoc_src_parser_js_102.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_cli_js_21._c_anonymous_24(Unknown Source)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_cli_js_21.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_cli_js_21._c_anonymous_16(Unknown Source)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_cli_js_21.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_cli_js_21._c_anonymous_10(Unknown Source)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_cli_js_21.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_jsdoc_js_1._c_anonymous_4(Unknown Source)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_jsdoc_js_1.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_jsdoc_js_1._c_script_0(Unknown Source)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_jsdoc_js_1.call(Unknown Source)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3090)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_jsdoc_js_1.call(Unknown Source)
        at org.mozilla.javascript.gen.file__home_asc_projects_jsdoc_jsdoc_js_1.exec(Unknown Source)
        at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:355)
        at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:288)
        at org.mozilla.javascript.commonjs.module.Require.requireMain(Require.java:137)
        at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:525)
        at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:176)
        at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:100)
        at org.mozilla.javascript.Context.call(Context.java:489)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
        at org.mozilla.javascript.tools.shell.Main.exec(Main.java:158)
        at org.mozilla.javascript.tools.shell.Main.main(Main.java:136)
Caused by: java.lang.IllegalArgumentException: No enum constant org.jsdoc.AstBuilder.NodeTypes.XmlMemberGet
        at java.lang.Enum.valueOf(Enum.java:236)
        at org.jsdoc.AstBuilder$NodeTypes.valueOf(AstBuilder.java:47)
        at org.jsdoc.AstBuilder.processNode(AstBuilder.java:352)
        at org.jsdoc.AstBuilder.processInfixExpression(AstBuilder.java:721)
        at org.jsdoc.AstBuilder.processNode(AstBuilder.java:432)
        at org.jsdoc.AstBuilder.processInfixExpression(AstBuilder.java:721)
        at org.jsdoc.AstBuilder.processNode(AstBuilder.java:432)
        at org.jsdoc.AstBuilder.processNodeList(AstBuilder.java:328)
        at org.jsdoc.AstBuilder.processFunctionCall(AstBuilder.java:686)
        at org.jsdoc.AstBuilder.processNode(AstBuilder.java:423)
        at org.jsdoc.AstBuilder.processExpressionStatement(AstBuilder.java:658)
        at org.jsdoc.AstBuilder.processNode(AstBuilder.java:414)
        at org.jsdoc.AstBuilder.processNodeList(AstBuilder.java:328)
        at org.jsdoc.AstBuilder.processNodeChildren(AstBuilder.java:344)
        at org.jsdoc.AstBuilder.processScope(AstBuilder.java:864)
        at org.jsdoc.AstBuilder.processNode(AstBuilder.java:476)
        at org.jsdoc.AstBuilder.processForInLoop(AstBuilder.java:667)
        at org.jsdoc.AstBuilder.processNode(AstBuilder.java:417)
        at org.jsdoc.AstBuilder.processNodeList(AstBuilder.java:328)
        at org.jsdoc.AstBuilder.processNodeChildren(AstBuilder.java:344)
        at org.jsdoc.AstBuilder.processBlock(AstBuilder.java:574)
        at org.jsdoc.AstBuilder.processNode(AstBuilder.java:376)
        at org.jsdoc.AstBuilder.processFunctionNode(AstBuilder.java:699)
        at org.jsdoc.AstBuilder.processNode(AstBuilder.java:426)
        at org.jsdoc.AstBuilder.processAssignment(AstBuilder.java:560)
        at org.jsdoc.AstBuilder.processNode(AstBuilder.java:370)
        at org.jsdoc.AstBuilder.processExpressionStatement(AstBuilder.java:658)
        at org.jsdoc.AstBuilder.processNode(AstBuilder.java:414)
        at org.jsdoc.AstBuilder.processNodeList(AstBuilder.java:328)
        at org.jsdoc.AstBuilder.processNodeChildren(AstBuilder.java:344)
        at org.jsdoc.AstBuilder.processAstRoot(AstBuilder.java:567)
        at org.jsdoc.AstBuilder.processNode(AstBuilder.java:373)
        at org.jsdoc.AstBuilder.build(AstBuilder.java:140)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
        ... 39 more
undefined

**Comment by hegemonic** [comment]
JSDoc does not support E4X syntax. You might try [creating a `beforeParse` plugin](http://usejsdoc.org/about-plugins.html#event-beforeparse) that strips this syntax from the source file.

**Comment by CardContact** [comment]
Wouldn't it be easier to have some markup that instructs jsdoc to ignore sections of the file , i.e. sections containing E4X code ?

**Comment by yaycmyk** [comment]
@CardContact No, because the whole file must be consumed by the AST generator (Esprima / Espree) before the individual comments can be processed.
