### ISSUE TITLE
The test (--test) throw an error

### ISSUE THREAD

**Issue by jerjako** [jsdoc3/jsdoc#1116]
Hi,

I use this command to generate a documentation 
<pre>
jsdoc ./ -r -d "doc" -R "README.md" -p
</pre>

I work perfecty, but when I want to juste "test", i have this error

<pre>
[ /var/www/framework/app ] jsdoc -T --match tag --verbose
module.js:339
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/jsdoc/test/runner'
    at Function.Module._resolveFilename (module.js:337:15)
    at Requizzle.requizzle (/usr/local/lib/node_modules/jsdoc/node_modules/requizzle/lib/requizzle.js:87:22)
    at infectProxy (/usr/local/lib/node_modules/jsdoc/node_modules/requizzle/lib/loader.js:82:28)
    at Module.targetModule.require (/usr/local/lib/node_modules/jsdoc/node_modules/requizzle/lib/loader.js:101:11)
    at require (module.js:385:17)
    at module.exports.cli.runTests (/usr/local/lib/node_modules/jsdoc/cli.js:200:36)
    at Object.module.exports.cli.runCommand (/usr/local/lib/node_modules/jsdoc/cli.js:180:5)
    at /usr/local/lib/node_modules/jsdoc/jsdoc.js:103:9
    at Object.<anonymous> (/usr/local/lib/node_modules/jsdoc/jsdoc.js:104:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
</pre>

**Comment by hegemonic** [comment]
My guess is that you installed JSDoc through npm. If so, JSDoc won't include the test files, so the `-T` option won't work.
