### ISSUE TITLE
JSDoc chokes on @param {String} headers['X-My-Header']

### ISSUE THREAD

**Issue by nfriedly** [jsdoc3/jsdoc#1178]
Hi, I have a bit of a conundrum: I have a method that accepts an options object. A couple of the options are headers which use dashes instead of camel case. I'd like to run both JSDoc and eslint on my code, but I can't seem to find a way to document the options that makes both happy.

This works for JSDoc, but confuses eslint's [valid-jsdoc](http://eslint.org/docs/rules/valid-jsdoc) rule, causing my tests to fail:

```js
/**
 * Example
 *
 * @param {Object} options
 * @param {String} [options.X-My-Header] custom header
 * @returns {*}
 */
function example(options) {
  // ...
}
```

The error from eslint is 
>   26:1  warning  Missing JSDoc parameter type for 'String'  valid-jsdoc

Meanwhile, this passes eslint, but then causes JSDoc to explode
```js
/**
 * Example
 *
 * @param {Object} options
 * @param {String} [options['X-My-Header']] custom header
 * @returns {*}
 */
function example(options) {
  // ...
}
```

The error is

```
            paramRegExp = new RegExp('^(?:' + parentParam.name + '(?:\\[\\])*)\\.(.+)$');
                          ^

SyntaxError: Invalid regular expression: /^(?:options['X-My-Header'](?:\[\])*)\.(.+)$/: Range out of order in character class
    at new RegExp (native)
    at eval (eval at <anonymous> (/Users/nfriedly/watson-speech/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:19:27)
    at Array.forEach (native)
    at eval (eval at <anonymous> (/Users/nfriedly/watson-speech/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:11:12)
    at template (/Users/nfriedly/watson-speech/node_modules/jsdoc/node_modules/underscore/underscore.js:1461:21)
    at exports.Template.partial (/Users/nfriedly/watson-speech/node_modules/jsdoc/lib/jsdoc/template.js:60:29)
    at eval (eval at <anonymous> (/Users/nfriedly/watson-speech/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:56:14)
    at template (/Users/nfriedly/watson-speech/node_modules/jsdoc/node_modules/underscore/underscore.js:1461:21)
    at exports.Template.partial (/Users/nfriedly/watson-speech/node_modules/jsdoc/lib/jsdoc/template.js:60:29)
    at eval (eval at <anonymous> (/Users/nfriedly/watson-speech/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:207:14)
    at Array.forEach (native)
    at eval (eval at <anonymous> (/Users/nfriedly/watson-speech/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:205:10)
    at Array.forEach (native)
    at eval (eval at <anonymous> (/Users/nfriedly/watson-speech/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:10:10)
    at template (/Users/nfriedly/watson-speech/node_modules/jsdoc/node_modules/underscore/underscore.js:1461:21)
    at exports.Template.partial (/Users/nfriedly/watson-speech/node_modules/jsdoc/lib/jsdoc/template.js:60:29)
```

Arguably this is really an eslint issue, and I filled https://github.com/eslint/eslint/issues/5612 to resolve that, but I still figured you guys might want to know about it too. 

I think something simple like escaping `[` and `]` before creating the regex might be good enough, to keep JSDoc from exploding.

**Comment by hegemonic** [comment]
Sorry, but I agree that this is an ESLint/Doctrine issue, not a JSDoc issue.
