### ISSUE TITLE
Two incorrect param entries {type specification) make JSDoc crash

### ISSUE THREAD

**Issue by peter-kehl** [jsdoc3/jsdoc#1221]
The following makes JSDoc crash. The problem happens only when at least two `@param` entries have the type starting with `{` but ending with `)`.

```
     /**@param {object) refused An object.
     *  @param {object) ignored An object.
     * */
    function Detector( refused, ignored ) {
    }
```

This is not a duplicate of https://github.com/jsdoc3/jsdoc/issues/1071. Below is an error stack, replicable with either 
- JSDoc 3.4.0 (Tue, 10 Nov 2015 00:28:09 GMT)
- JSDoc 3.5.0-dev (Thu, 03 Dec 2015 14:03:57 GMT)

```
undefined:18
            paramRegExp = new RegExp('^(?:' + parentParam.name + '(?:\\[\\])*)
                          ^
SyntaxError: Invalid regular expression: /^(?:{object)(?:\[\])*)\.(.+)$/: Unmatched ')'
    at new RegExp (<anonymous>)
    at params.hasAttributes (eval at <anonymous> (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:18:27)
    at Array.forEach (native)
    at eval (eval at <anonymous> (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:10:12)
    at template (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1461:21)
    at exports.Template.partial (/usr/lib/node_modules/jsdoc/lib/jsdoc/template.js:60:29)
    at eval (eval at <anonymous> (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:55:14)
    at template (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1461:21)
    at exports.Template.partial (/usr/lib/node_modules/jsdoc/lib/jsdoc/template.js:60:29)
    at eval (eval at <anonymous> (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:206:14)
    at Array.forEach (native)
    at eval (eval at <anonymous> (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:204:10)
    at Array.forEach (native)
    at eval (eval at <anonymous> (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:9:10)
    at template (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1461:21)
    at exports.Template.partial (/usr/lib/node_modules/jsdoc/lib/jsdoc/template.js:60:29)
```

**Comment by hegemonic** [comment]
Fixed on master and releases/3.5. The fix will be included in JSDoc 3.5.2.
