### ISSUE TITLE
new unknown Error

### ISSUE THREAD

**Issue by pixelass** [jsdoc3/jsdoc#1254]
Unsure how to describe this error but it simply fails when I run this:

## command

```shell
rm -rf docs && mkdir docs && jsdoc -c jsdoc.json
```

## expected

Generate docs for one function

## result

```
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.exports.ls (/Users/<ME:REPO>/node_modules/jsdoc/lib/jsdoc/fs.js:40:20)
    at Object.exports.load (/Users/<ME:REPO>/node_modules/jsdoc/lib/jsdoc/tutorial/resolver.js:110:20)
    at Object.module.exports.cli.resolveTutorials (/Users/<ME:REPO>/node_modules/jsdoc/cli.js:397:18)
    at Object.module.exports.cli.processParseResults (/Users/<ME:REPO>/node_modules/jsdoc/cli.js:382:13)
    at module.exports.cli.main (/Users/<ME:REPO>/node_modules/jsdoc/cli.js:227:14)
    at Object.module.exports.cli.runCommand (/Users/<ME:REPO>/node_modules/jsdoc/cli.js:180:5)
    at /Users/<ME:REPO>/node_modules/jsdoc/jsdoc.js:103:9
    at Object.<anonymous> (/Users/<ME:REPO>/node_modules/jsdoc/jsdoc.js:104:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
```

### jsdoc.json
```json
{
  "tags": {
    "allowUnknownTags": true,
    "dictionaries": ["jsdoc"]
  },
  "plugins": [
    "plugins/markdown",
    "plugins/commentsOnly"
  ],
  "templates": {
    "cleverLinks": true,
    "monospaceLinks": true
  },
  "source": {
    "include": ["packages/foobar"],
    "includePattern": "\\.js$",
    "excludePattern": "(node_modules/)"
  },
  "opts": {
    "encoding": "utf8",
    "destination": "./docs/",
    "private": true,
    "tutorials": true,
    "recurse": true,
    "template": "node_modules/hopsdoc"
  }
}
```

### packages/foobar/index.js

```js
/**
 * fobbar should work
 * @param  {*} foo anything since not used
 * @return {string} always returns 'bar'
 */
const foobar = (foo) => 'bar'
```

**Comment by hegemonic** [comment]
I think you're seeing this error because in `jsdoc.json`, the property `opts.tutorials` is supposed to be the path to the tutorials, rather than a boolean.
