### ISSUE TITLE
jsdoc crashs when parsing empty tags which requires a value

### ISSUE THREAD

**Issue by roipoussiere** [jsdoc3/jsdoc#1289]
Given this code:

``` js
/**
 * @author
 */
var s = "test_jsdoc";
```

jsdoc crashs with this stacktrace:

```
ERROR: The @author tag requires a value. File: test_jsdoc.js, line: 1
ERROR: The @author tag requires a value. File: test_jsdoc.js, line: 4
/usr/lib/node_modules/jsdoc/lib/jsdoc/util/templateHelper.js:554
    var matches = str.match(/^\s?([\s\S]+)\b\s+<(\S+@\S+)>\s?$/);
                     ^

TypeError: Cannot read property 'match' of undefined
    at exports.resolveAuthorLinks (/usr/lib/node_modules/jsdoc/lib/jsdoc/util/templateHelper.js:554:22)
    at eval (eval at <anonymous> (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:100:14)
    at Array.forEach (native)
    at eval (eval at <anonymous> (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:98:9)
    at template (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1461:21)
    at exports.Template.partial (/usr/lib/node_modules/jsdoc/lib/jsdoc/template.js:60:29)
    at eval (eval at <anonymous> (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:33:14)
    at template (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1461:21)
    at exports.Template.partial (/usr/lib/node_modules/jsdoc/lib/jsdoc/template.js:60:29)
    at eval (eval at <anonymous> (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:194:14)
    at Array.forEach (native)
    at eval (eval at <anonymous> (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:192:10)
    at Array.forEach (native)
    at eval (eval at <anonymous> (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:10:10)
    at template (/usr/lib/node_modules/jsdoc/node_modules/underscore/underscore.js:1461:21)
    at exports.Template.partial (/usr/lib/node_modules/jsdoc/lib/jsdoc/template.js:60:29)
```

Ok, the code is not good, because the `@author` tag requires a value. But this should only print an ERROR.

**Comment by hegemonic** [comment]
Fixed on master. The fix will be included in JSDoc 3.5.0.
