### ISSUE TITLE
Disable lint

### ISSUE THREAD

**Issue by unbug** [jsdoc3/jsdoc#1298]
Currently jsdoc doesn't support ES7, the process will failed if we use some ES7 syntax, such as class properties. Can we just ignore instead of throw a error and don't stop generate the progress?

```
Message:
    ERROR: Unable to parse /myProject/lib/Player.js: Unexpected token =
Stack:
JSDOC_ERROR: ERROR: Unable to parse /myProject/lib/Player.js: Unexpected token =
    at Explain.verifyOutput (/myProject/node_modules/jsdoc-api/lib/jsdoc-command.js:113:19)
    at ChildProcess.handle.on.err (/myProject/node_modules/jsdoc-api/lib/explain.js:48:38)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

```

**Comment by hegemonic** [comment]
This isn't a lint error--the problem is that our JavaScript parser doesn't understand the syntax. Sorry, but there's nothing I can do about it. I believe there are plugins that preprocess JS code with Babel before feeding it to JSDoc, but unfortunately, I can't tell you where to find them.
