### ISSUE TITLE
Add meaningfull error message when require'ing jsdoc module directly

### ISSUE THREAD

**Issue by Ginden** [jsdoc3/jsdoc#1369]
Simple test case:

```shell
$ mkdir test && cd test && npm init -y && npm install jsdoc --silent && node -e "require('jsdoc')"
```

Result:

```
Error: Cannot find module 'jsdoc'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

Expected result:

```
Error: jsdoc module isn't supposed to be used programatically
     at ... (node_modules/jsdoc/index.js: 1:1)
```

**Comment by hegemonic** [comment]
I'm happy to implement this, but I'm not sure how. I'd welcome some pointers (or a pull request).
