### ISSUE TITLE
Version 3.5.0 causes command to fail

### ISSUE THREAD

**Issue by robCam** [jsdoc3/jsdoc#1392]
### Issue
As expected, running the following via the command-line worked successfully using version **3.4.3**:

`node_modules/.bin/jsdoc -R README.md some-file.js -d ./docs`

However, since the **3.5.0** patch the command above fails.

### Error Log

The following error is logged utilizing version **3.5.0**:

**Note:** _`path-to-project` instances below represent a real path_

> path-to-project/node_modules/babylon/lib/index.js:164
bleConstructorReturn(this, _TokenType2.call(this, name, { beforeExpr, binop: p
                                                                    ^
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Object.load (path-to-project/node_modules/requizzle/lib/loader.js:112:15)
    at Requizzle.requizzle (path-to-project/node_modules/requizzle/lib/requizzle.js:90:24)
    at infectProxy (path-to-project/node_modules/requizzle/lib/loader.js:82:28)
    at Module.targetModule.require (path-to-project/node_modules/requizzle/lib/loader.js:101:11)
    at require (module.js:380:17)
    at Object.<anonymous> (path-to-project/node_modules/jsdoc/lib/jsdoc/src/astbuilder.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Object.load (path-to-project/node_modules/requizzle/lib/loader.js:112:15)
    at Requizzle.requizzle (path-to-project/node_modules/requizzle/lib/requizzle.js:90:24)
    at infectProxy (path-to-project/node_modules/requizzle/lib/loader.js:82:28)
    at Module.targetModule.require (path-to-project/node_modules/requizzle/lib/loader.js:101:11)

### Additional notes:

The error above is reported in the following system environments:
- nodejs v0.10.28 - running on Mac OSX.
- nodejs v0.12.3 - running on Windows Vista.

**Comment by hegemonic** [comment]
JSDoc now requires Node.js 4.2.0 or later. Please upgrade Node.js and try again.

**Comment by robCam** [comment]
Thanks @hegemonic for highlighting the Node.js 4.2.0 minimum requirement for JSDoc 3.5.x - just read the updated README.

Interestingly, several of my projects started failing today after running `$ npm install` as JSDoc was defined in  `package.json` as `"jsdoc": "^3.4.3"` (i.e. It utilizes npm's default `save-prefix` the caret `^`). I think I'll retrospectively set them to to use the tilde (`~`) to avoid the issue reoccurring on node.js environments < 4.2.0.

I appreciate that the Minor release of JSDocs adds functionality in backwards-compatible manner. However, perhaps the greater Node.js dependency constitues a Major release for JSDocs instead of it being a Minor one. I guess this is a bit of a grey area regarding semver.

Once again, thanks for the prompt reply - much appreciated.

**Comment by hegemonic** [comment]
You're quite welcome!

Right now, JSDoc doesn't really follow semver. I know this is a source of frustration for a lot of people, and I may change my policy on this in the future. For now, though, using the tilde for JSDoc is your safest bet.
