### ISSUE TITLE
Static variable assignment in decorator breaks things

### ISSUE THREAD

**Issue by berfarah** [jsdoc3/jsdoc#1419]
Hi! I came across this bug today. Please let me know if there's any thing I can clarify / improve on this issue.

### JSDoc debug output

```
DEBUG: JSDoc 3.5.3 (Fri, 14 Jul 2017 02:48:27 GMT)
DEBUG: Environment info: {"env":{"conf":{"plugins":[],"recurseDepth":10,"source":{"includePattern":".+\\.js(doc|x)?$","excludePattern":"(^|\\/|\\\\)_"},"sourceType":"module","tags":{"allowUnknownTags":true,"dictionaries":["jsdoc","closure"]},"templates":{"monospaceLinks":false,"cleverLinks":false,"default":{"outputSourceFiles":true}}},"opts":{"_":["src/model/store.js"],"debug":true,"destination":"./out/","encoding":"utf8"}}}
DEBUG: Parsing source files: ["/Users/bernardo/dev/coverhound/active-redux/src/model/store.js"]
Parsing /Users/bernardo/dev/coverhound/active-redux/src/model/store.js ...
/Users/bernardo/dev/coverhound/active-redux/node_modules/jsdoc/lib/jsdoc/src/parser.js:360
        result.memberof = doclet.longname + jsdoc.name.SCOPE.PUNC.INSTANCE;
                                ^

TypeError: Cannot read property 'longname' of null
    at Parser.astnodeToMemberof (/Users/bernardo/dev/coverhound/active-redux/node_modules/jsdoc/lib/jsdoc/src/parser.js:360:33)
    at addSymbolMemberof (/Users/bernardo/dev/coverhound/active-redux/node_modules/jsdoc/lib/jsdoc/src/handlers.js:270:31)
    at newSymbolDoclet (/Users/bernardo/dev/coverhound/active-redux/node_modules/jsdoc/lib/jsdoc/src/handlers.js:300:13)
    at .<anonymous> (/Users/bernardo/dev/coverhound/active-redux/node_modules/jsdoc/lib/jsdoc/src/handlers.js:367:13)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Visitor.visitNode (/Users/bernardo/dev/coverhound/active-redux/node_modules/jsdoc/lib/jsdoc/src/visitor.js:594:16)
    at Visitor.visit (/Users/bernardo/dev/coverhound/active-redux/node_modules/jsdoc/lib/jsdoc/src/visitor.js:484:27)
    at Walker.recurse (/Users/bernardo/dev/coverhound/active-redux/node_modules/jsdoc/lib/jsdoc/src/walker.js:701:38)
    at Parser._walkAst (/Users/bernardo/dev/coverhound/active-redux/node_modules/jsdoc/lib/jsdoc/src/parser.js:265:18)
    at Parser._parseSourceCode (/Users/bernardo/dev/coverhound/active-redux/node_modules/jsdoc/lib/jsdoc/src/parser.js:256:18)
    at Parser.parse (/Users/bernardo/dev/coverhound/active-redux/node_modules/jsdoc/lib/jsdoc/src/parser.js:179:18)
    at Object.module.exports.cli.parseFiles (/Users/bernardo/dev/coverhound/active-redux/node_modules/jsdoc/cli.js:370:42)
    at module.exports.cli.main (/Users/bernardo/dev/coverhound/active-redux/node_modules/jsdoc/cli.js:239:14)
    at Object.module.exports.cli.runCommand (/Users/bernardo/dev/coverhound/active-redux/node_modules/jsdoc/cli.js:189:5)
    at /Users/bernardo/dev/coverhound/active-redux/node_modules/jsdoc/jsdoc.js:105:9
```

#### Minimum code to reproduce:
```js
export default (target) => (
  class Model extends target {
    static context = {};
  }
);
```

#### This apparently works:
```js
export default (target) => (
  class Model extends target {
  }
);
```

### Expected behavior

JSDoc not to crash

### Current behavior

JSDoc crashing at the point seen above

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5.3
| Node.js          | 6.10.0
| npm              | 3.10.10
| yarn              | 0.27.5
| Operating system | Mac OS 10.12.5

**Comment by hegemonic** [comment]
This looks like the same issue as #1416, which is fixed on GitHub master and releases/3.5. The fix will be included in JSDoc 3.5.4, which I plan to release within the next week or so.

**Comment by berfarah** [comment]
Oop, sorry, missed it. Thanks!

**Comment by hegemonic** [comment]
No worries, @berfarah! I had to run a test to confirm that you were seeing the same issue—it wasn't super-obvious.
