### ISSUE TITLE
jsdoc fails to parse and throws a TypeError

### ISSUE THREAD

**Issue by tasstwa** [jsdoc3/jsdoc#1516]
### Input code

This simple file ends up throwing jsdoc:
```js
var c = {
    o: [
        class apdc extends cccb {
            constructor() {
            }

        }]
};
```

### JSDoc configuration

I am using no particular jsdoc config.

### JSDoc debug output

```
        if (doclet.memberof) {
                   ^

TypeError: Cannot read property 'memberof' of null
    at exports.Parser.Parser.astnodeToMemberof (/home/mgadbois/ads/build/topic-sc/Default/opusone/webui/jscripts/node_modules/jsdoc/lib/jsdoc/src/parser.js:371:2
0)
    at addSymbolMemberof (/home/mgadbois/ads/build/topic-sc/Default/opusone/webui/jscripts/node_modules/jsdoc/lib/jsdoc/src/handlers.js:270:31)
    at newSymbolDoclet (/home/mgadbois/ads/build/topic-sc/Default/opusone/webui/jscripts/node_modules/jsdoc/lib/jsdoc/src/handlers.js:300:13)
    at exports.Parser.<anonymous> (/home/mgadbois/ads/build/topic-sc/Default/opusone/webui/jscripts/node_modules/jsdoc/lib/jsdoc/src/handlers.js:367:13)
    at emitTwo (events.js:126:13)
    at exports.Parser.emit (events.js:214:7)
    at exports.Visitor.Visitor.visitNode (/home/mgadbois/ads/build/topic-sc/Default/opusone/webui/jscripts/node_modules/jsdoc/lib/jsdoc/src/visitor.js:594:16)
    at exports.Visitor.Visitor.visit (/home/mgadbois/ads/build/topic-sc/Default/opusone/webui/jscripts/node_modules/jsdoc/lib/jsdoc/src/visitor.js:484:27)
    at exports.Walker.Walker.recurse (/home/mgadbois/ads/build/topic-sc/Default/opusone/webui/jscripts/node_modules/jsdoc/lib/jsdoc/src/walker.js:699:38)
    at exports.Parser.Parser._walkAst (/home/mgadbois/ads/build/topic-sc/Default/opusone/webui/jscripts/node_modules/jsdoc/lib/jsdoc/src/parser.js:265:18)
    at exports.Parser.Parser._parseSourceCode (/home/mgadbois/ads/build/topic-sc/Default/opusone/webui/jscripts/node_modules/jsdoc/lib/jsdoc/src/parser.js:256:18
)
    at exports.Parser.Parser.parse (/home/mgadbois/ads/build/topic-sc/Default/opusone/webui/jscripts/node_modules/jsdoc/lib/jsdoc/src/parser.js:179:18)
    at Object.module.exports.cli.parseFiles (/home/mgadbois/ads/build/topic-sc/Default/opusone/webui/jscripts/node_modules/jsdoc/cli.js:370:42)
    at module.exports.cli.main (/home/mgadbois/ads/build/topic-sc/Default/opusone/webui/jscripts/node_modules/jsdoc/cli.js:239:14)
    at Object.module.exports.cli.runCommand (/home/mgadbois/ads/build/topic-sc/Default/opusone/webui/jscripts/node_modules/jsdoc/cli.js:189:5)

```

### Expected behavior
No failure.

### Current behavior
Throws on doclet === null

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | JSDoc 3.5.5 (Thu, 14 Sep 2017 02:51:54 GMT)
| Node.js          | v8.9.4
| npm              | 5.6.0
| Operating system | Linux Mint 17.2 rafaela

**Comment by ashwani-raj** [comment]
I am getting same error, is there a workaround for this?

**Comment by HunterKohler** [comment]
+1

**Comment by egasimus** [comment]
Well it sure looks to me like JSDoc doesn't support classes that are not defined at the top level? This just bit me in the ass and now I have to restructure the whole module. Hope I've understood it correctly...

**Comment by atjn** [comment]
I'm running into the same issue on https://github.com/atjn/blockchain-visualizer
I have lots of classes defined all over the place, so @egasimus explanation sounds plausible :)

**Comment by giraypultar** [comment]
A workaround is to change one line:`
node_modules/jsdoc/lib/jsdoc/src/parser.js:371`

Instead of:`
if (doclet.memberof) {`

change it to:`
if (doclet && doclet.memberof) {`


This way, at least jsdoc ca run. I am not sure if the class inside is accessible.
