### ISSUE TITLE
How to use JSDoc3 with some .c files? (Some lines of code begin with #include, but # is read as an illegal character)

### ISSUE THREAD

**Issue by cordom2** [jsdoc3/jsdoc#1553]
I am currently trying to use JSDoc 3 to generate a documentation guide in HTML. Some of the files I am using to make the guide are .h and .c files that contain lines of code beginning with #include and #ifndef. 

However, when I run the jsdoc, I get an error from those lines saying that # is an illegal character. Is there some sort of plugin I can write to correct this issue? How can I run my project without getting an error for the lines of code beginning with #?

This documentation guide used to be generated using JSDoc2. When JSDoc2 was used I was able to generate the document from a combination of javascript, html templates, .c, and .h files. Now that I need to update the documentation guide to be generated using JSDoc3 I cannot get the process to work. I am sure there is some way to make it work since it was doable on the older, outdated version of JSDoc, but I am not sure how to make it work and am having some difficulty finding relevant material online. Any help towards finding a solution for this would be greatly appreciated.

### JSDoc configuration

```js
{
    "tags": {
        "allowUnknownTags": true
    },
    "source": {
        "includePattern": ".+\\.js(doc|x)?$",
	"includePattern": ".+\\.c(doc|x)?$",
	"includePattern": ".+\\.h(doc|x)?$",
        "excludePattern": "(^|\\/|\\\\)_"
    },
    "plugins": [],
    "templates": {
        "cleverLinks": false,
        "monospaceLinks": false,
        "default": {
            "outputSourceFiles": true,
	    "layoutFile": "./home/cordonem/bitbucket/workdir/lib/defaults/platform/docs/templates/html"
        }
    }
}

```

### JSDoc debug output

I ran a debug and got the result that there were no failures, so this issue does not appear to be a bug.

### Expected behavior

The JSDoc is expected to generate a documentation guide. Instead, I get the error readout displayed below in which the **#** symbol at the beginning of lines of code is read as an illegal character and causes the compilation to fail.

### Current behavior

js: "/home/cordonem/bitbucket/workdir/src/isl/binder/common/common.h", line 41: illegal character
js: #ifndef ITS_ISL_BINDER_COMMON_H__
js: ^
org.mozilla.javascript.EvaluatorException: Compilation produced 1 syntax errors. (/home/cordonem/bitbucket/workdir/src/isl/binder/common/common.h#1)
        at org.mozilla.javascript.tools.ToolErrorReporter.runtimeError(ToolErrorReporter.java:144)
        at org.mozilla.javascript.Parser.parse(Parser.java:596)
        at org.mozilla.javascript.Parser.parse(Parser.java:505)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:247)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
        at org.mozilla.javascript.gen.file__ws_linopt_jsdoc_jsdoc_3_2_2_node_modules_jsdoc_src_parser_js_18._c_anonymous_23(Unknown Source)
        at org.mozilla.javascript.gen.file__ws_linopt_jsdoc_jsdoc_3_2_2_node_modules_jsdoc_src_parser_js_18.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
        at org.mozilla.javascript.gen.file__ws_linopt_jsdoc_jsdoc_3_2_2_node_modules_jsdoc_src_parser_js_18._c_anonymous_2(Unknown Source)
        at org.mozilla.javascript.gen.file__ws_linopt_jsdoc_jsdoc_3_2_2_node_modules_jsdoc_src_parser_js_18.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
        at org.mozilla.javascript.gen._ws_linopt_jsdoc_jsdoc_3_2_2_jsdoc_js_1._c_main_3(Unknown Source)
        at org.mozilla.javascript.gen._ws_linopt_jsdoc_jsdoc_3_2_2_jsdoc_js_1.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
        at org.mozilla.javascript.gen._ws_linopt_jsdoc_jsdoc_3_2_2_jsdoc_js_1._c_script_0(Unknown Source)
        at org.mozilla.javascript.gen._ws_linopt_jsdoc_jsdoc_3_2_2_jsdoc_js_1.call(Unknown Source)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3178)
        at org.mozilla.javascript.gen._ws_linopt_jsdoc_jsdoc_3_2_2_jsdoc_js_1.call(Unknown Source)
        at org.mozilla.javascript.gen._ws_linopt_jsdoc_jsdoc_3_2_2_jsdoc_js_1.exec(Unknown Source)
        at org.mozilla.javascript.tools.shell.Main.evaluateScript(Main.java:654)
        at org.mozilla.javascript.tools.shell.Main.processFileSecure(Main.java:552)
        at org.mozilla.javascript.tools.shell.Main.processFile(Main.java:507)
        at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:499)
        at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:215)
        at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:134)
        at org.mozilla.javascript.Context.call(Context.java:521)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:535)
        at org.mozilla.javascript.tools.shell.Main.exec(Main.java:198)
        at org.mozilla.javascript.tools.shell.Main.main(Main.java:174)

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5.5
| Node.js          |
| npm              |
| Operating system | Linux version 2.6.32-696.30.1.el6.x86_64

**Comment by gibatronic** [comment]
`JSDoc` is meant for... JS.
it seems that for C/C++ people use `Doxygen`

**Comment by usernamefghh** [comment]
b

**Comment by hegemonic** [comment]
You could try using JSDoc's [`commentsOnly` plugin](https://github.com/jsdoc3/jsdoc/blob/master/plugins/commentsOnly.js) for this purpose. But yeah, you're probably better off using Doxygen or some other tool that can parse C source files. JSDoc is intended for JavaScript.
