### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by domahoneyii** [jsdoc3/jsdoc#1623]
I have nuxtjs app with a vue component that I want to document. This behavior only happens in my nuxtjs app. All my vue apps documentation work fine.

The complete text of the error message is: 

```
Error: ENOENT: no such file or directory, stat '/Applications/Gitter.app/Contents/Frameworks/SocketRocket.framework/Modules'
```
Command:

```
jsdoc -c doc.conf.js
```

### JSDoc configuration
```
module.exports = {
  opts: {
    destination: 'generated-files/doc',
    recurse: true,
  },
  recurseDepth: 10,
  plugins: [
    'plugins/markdown',
    'node_modules/jsdoc-vue',
  ],
  source: {
    includePattern: '.+\\.(vue|js)$',
    include: [
      'src',
      'package.json',
      'README.md',
    ],
    exclude: [
      'src/middleware',
      'src/plugins',
    ],
  },
};
```

Stack Trace:

```
jsdoc -c doc.conf.js
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, stat '/Applications/Gitter.app/Contents/Frameworks/SocketRocket.framework/Modules'
    at Object.statSync (fs.js:871:3)
    at exports.ls (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/fs.js:51:17)
    at exports.ls (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/fs.js:56:17)
    at exports.ls (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/fs.js:56:17)
    at exports.ls (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/fs.js:56:17)
    at exports.ls (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/fs.js:56:17)
    at Object.exports.ls (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/fs.js:56:17)
    at /usr/local/lib/node_modules/jsdoc/lib/jsdoc/src/scanner.js:51:46
    at Array.forEach (<anonymous>)
    at exports.Scanner.scan (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/src/scanner.js:35:17)
    at Object.module.exports.cli.scanFiles (/usr/local/lib/node_modules/jsdoc/cli.js:316:45)
    at module.exports.cli.main (/usr/local/lib/node_modules/jsdoc/cli.js:231:9)
    at Object.module.exports.cli.runCommand (/usr/local/lib/node_modules/jsdoc/cli.js:189:5)
    at /usr/local/lib/node_modules/jsdoc/jsdoc.js:105:9
    at Object.<anonymous> (/usr/local/lib/node_modules/jsdoc/jsdoc.js:106:3)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
```

### JSDoc debug output

```
jsdoc -c doc.conf.js --debug
DEBUG: JSDoc 3.5.5 (Thu, 14 Sep 2017 02:51:54 GMT)
DEBUG: Environment info: {"env":{"conf":{"plugins":["plugins/markdown","node_modules/jsdoc-vue"],"recurseDepth":10,"source":{"includePattern":".+\\.(vue|js)$","excludePattern":"","include":["/","package.json","README.md"],"exclude":["middleware","plugins"]},"sourceType":"module","tags":{"allowUnknownTags":true,"dictionaries":["jsdoc","closure"]},"templates":{"monospaceLinks":false,"cleverLinks":false},"opts":{"destination":"generated-files/doc","recurse":true}},"opts":{"_":[],"configure":"doc.conf.js","debug":true,"destination":"generated-files/doc","recurse":true,"encoding":"utf8"}}}
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, stat '/Applications/Gitter.app/Contents/Frameworks/SocketRocket.framework/Modules'
    at Object.statSync (fs.js:871:3)
    at exports.ls (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/fs.js:51:17)
    at exports.ls (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/fs.js:56:17)
    at exports.ls (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/fs.js:56:17)
    at exports.ls (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/fs.js:56:17)
    at exports.ls (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/fs.js:56:17)
    at Object.exports.ls (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/fs.js:56:17)
    at /usr/local/lib/node_modules/jsdoc/lib/jsdoc/src/scanner.js:51:46
    at Array.forEach (<anonymous>)
    at exports.Scanner.scan (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/src/scanner.js:35:17)
    at Object.module.exports.cli.scanFiles (/usr/local/lib/node_modules/jsdoc/cli.js:316:45)
    at module.exports.cli.main (/usr/local/lib/node_modules/jsdoc/cli.js:231:9)
    at Object.module.exports.cli.runCommand (/usr/local/lib/node_modules/jsdoc/cli.js:189:5)
    at /usr/local/lib/node_modules/jsdoc/jsdoc.js:105:9
    at Object.<anonymous> (/usr/local/lib/node_modules/jsdoc/jsdoc.js:106:3)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
```

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5.5
| JSDoc-vue    | 1.0.0
| Node.js          | 1.10.0
| npm              | 6.8.0
| Operating system | macOS 10.13.6

**Comment by JustinBeaudry** [comment]
I wonder if this is because '/Applications/Gitter.app/Contents/Frameworks/SocketRocket.framework/Modules' is a symlink? 

Regardless, when following that symlink, it doesn't appear that `Modules` resolves to a directory at all.

**Comment by KouYangCHUEDOUESAYKAO** [comment]
dfdfgdf

**Comment by KouYangCHUEDOUESAYKAO** [comment]
Error: ENOENT: no such file or directory, open 'C:\Users\KouYang\Desktop\Node-JS\cms\views\layouts\home.handlebars'
