### ISSUE TITLE
jsdoc 3.3.0-beta2 fails where 3.3.0.beta1 was working

### ISSUE THREAD

**Issue by Xotic750** [jsdoc3/jsdoc#954]
Just did an `npm update` and now my project fails to build the docs, I have no idea why. Rolling `jsdoc` back to the previous version and all works again.
```
[graham@tyr util-x]$ uname -a
Linux tyr 3.14.27-100.fc19.x86_64 #1 SMP Wed Dec 17 19:36:34 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

[graham@tyr util-x]$ node -v
v0.10.28

[graham@tyr util-x]$ ./node_modules/.bin/jsdoc -v
JSDoc 3.3.0-beta2 (Sat, 07 Mar 2015 17:54:50 GMT)

[graham@tyr util-x]$ ./node_modules/.bin/jsdoc -d docs lib/util-x.js 

/home/graham/source_projects/util-x/node_modules/jsdoc/lib/jsdoc/tag.js:33
    return meta && meta.code && meta.code.name === text && text.match(/(?:^\s+
                                                                ^
TypeError: Object 1 has no method 'match'
    at mustPreserveWhitespace (/home/graham/source_projects/util-x/node_modules/jsdoc/lib/jsdoc/tag.js:33:65)
    at trim (/home/graham/source_projects/util-x/node_modules/jsdoc/lib/jsdoc/tag.js:43:10)
    at new exports.Tag (/home/graham/source_projects/util-x/node_modules/jsdoc/lib/jsdoc/tag.js:189:17)
    at Doclet.addTag (/home/graham/source_projects/util-x/node_modules/jsdoc/lib/jsdoc/doclet.js:199:18)
    at newSymbolDoclet (/home/graham/source_projects/util-x/node_modules/jsdoc/lib/jsdoc/src/handlers.js:256:19)
    at null.<anonymous> (/home/graham/source_projects/util-x/node_modules/jsdoc/lib/jsdoc/src/handlers.js:318:13)
    at EventEmitter.emit (events.js:98:17)
    at Visitor.visitNode (/home/graham/source_projects/util-x/node_modules/jsdoc/lib/jsdoc/src/visitor.js:281:16)
    at Visitor.visit (/home/graham/source_projects/util-x/node_modules/jsdoc/lib/jsdoc/src/visitor.js:191:27)
    at Walker.recurse (/home/graham/source_projects/util-x/node_modules/jsdoc/lib/jsdoc/src/walker.js:531:44)
```

**Comment by hegemonic** [comment]
I suspect you're running into an issue that was fixed after I released 3.3.0-beta2. Could you try the current version from GitHub master and see if that works?

**Comment by Xotic750** [comment]
The GitHub master solves this issue.
```
[graham@tyr util-x]$ ./node_modules/jsdoc/jsdoc -v
JSDoc 3.4.0-dev (Wed, 18 Feb 2015 03:07:23 GMT)

[graham@tyr util-x]$ ./node_modules/.bin/jsdoc --verbose -d docs lib/util-x.js 
Parsing /home/graham/source_projects/util-x/lib/util-x.js ...
Generating output files...
Finished running in 4.67 seconds
```

**Comment by hegemonic** [comment]
Yep, #945 is the likely culprit.

I just published 3.3.0-beta3, which includes the fix for #945. If you upgrade, you should be all set.

**Comment by Xotic750** [comment]
Thanks! Will give it a try.

**Comment by Xotic750** [comment]
Seems to work fine again. :)
