### ISSUE TITLE
error when some -but not all- parameters of a function have a default

### ISSUE THREAD

**Issue by mhelvens** [jsdoc3/jsdoc#978]
Run the following code through jsdoc-3.3.0-beta3:

    function f(a, b=5) {}

This will show the following error:

```
/home/mhelvens/Projects/js-graph-2/node_modules/jsdoc/lib/jsdoc/src/walker.js:497
        if (typeof node.parent !== 'undefined') {
                       ^
TypeError: Cannot read property 'parent' of undefined
    at cb (/home/mhelvens/Projects/js-graph-2/node_modules/jsdoc/lib/jsdoc/src/walker.js:497:24)
    at Object.arrowFunctionExpression (/home/mhelvens/Projects/js-graph-2/node_modules/jsdoc/lib/jsdoc/src/walker.js:82:9)
    at cb (/home/mhelvens/Projects/js-graph-2/node_modules/jsdoc/lib/jsdoc/src/walker.js:513:33)
    at Object.blockStatement (/home/mhelvens/Projects/js-graph-2/node_modules/jsdoc/lib/jsdoc/src/walker.js:104:9)
    at cb (/home/mhelvens/Projects/js-graph-2/node_modules/jsdoc/lib/jsdoc/src/walker.js:513:33)
    at Walker._recurse (/home/mhelvens/Projects/js-graph-2/node_modules/jsdoc/lib/jsdoc/src/walker.js:520:5)
    at Walker.recurse (/home/mhelvens/Projects/js-graph-2/node_modules/jsdoc/lib/jsdoc/src/walker.js:529:22)
    at Parser._walkAst (/home/mhelvens/Projects/js-graph-2/node_modules/jsdoc/lib/jsdoc/src/parser.js:245:18)
    at Parser._parseSourceCode (/home/mhelvens/Projects/js-graph-2/node_modules/jsdoc/lib/jsdoc/src/parser.js:235:18)
    at Parser.parse (/home/mhelvens/Projects/js-graph-2/node_modules/jsdoc/lib/jsdoc/src/parser.js:156:18)
```

**Comment by hegemonic** [comment]
This was already fixed on master. I fixed it on the releases/3.3 branch by cherry-picking 1e09e57a05cda9451dbb23ef97c52ef3a6854275. The fix will be included in the final release of JSDoc 3.3.0.

Thanks for the heads up!
